# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'simpleExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking'
  # Pods for simpleExample

  target 'simpleExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'simpleExampleUITests' do
    # Pods for testing
  end

end
